server:
#  port: 6119
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: board-svc
#          uri: http://localhost:8083
#          uri: http://board.test.com
          uri: http://10.107.154.31:8092
          predicates:
            - Path=/board/**
          filters:
            - name: BoardFilter
              args:
                baseMessage: Spring Cloud Gateway BoardFilter
                preLogger: true
                postLogger: true
        - id: user-svc
#          uri: http://localhost:8084
#          uri: http://user.test.com
          uri: http://10.107.154.32:8092
          predicates:
            - Path=/user/**
          filters:
            - name: UserFilter
              args:
                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
  application:
    name: gateway-server
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: immediate
  redis:
    host: 10.107.154.34
    port: 6379
    

# route정보 확인 (/actuator/gateway/routes)
management:
    endpoints:
        web:
            exposure:
                include:
                    - "gateway"
    endpoint:
        gateway:
            enabled: true
            
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      

