apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  ports:
    - name: "8090"
      port: 8092
      targetPort: 8090
      nodePort: 30010
  selector:
    app: gateway-api
  type: NodePort